/**
 * Genera los tipos de TypeScript de la base a partir del esquema real.
 *
 *   npm run db:types
 *
 * Escribe src/lib/db/schema.types.ts. Ese archivo NO se edita a mano: se
 * regenera cada vez que cambia la estructura de la base.
 *
 * ── POR QUÉ EXISTE ───────────────────────────────────────────────────────────
 *
 * Los tipos `*Row` de cada módulo (ProveedorRow, ArticuloRow…) describían las
 * columnas de la base y estaban escritos a mano. Nada los comparaba con la
 * tabla real, así que renombrar o borrar una columna compilaba perfecto y
 * fallaba recién en producción con un 42703 (`undefined_column`).
 *
 * Derivando los `*Row` de este archivo, ese mismo cambio pasa a ser un error de
 * compilación en `npm run typecheck`.
 *
 * ── EL DETALLE QUE HACE ÚTIL ESTE GENERADOR ──────────────────────────────────
 *
 * Los tipos que emite son los que devuelve el DRIVER `pg`, no los que dice SQL.
 * No es lo mismo:
 *
 *   numeric / decimal  →  string   (pg NO lo convierte, para no perder precisión)
 *   bigint             →  string   (no entra en un Number de JS)
 *   timestamp / date   →  Date
 *   integer            →  number
 *
 * Ese `numeric → string` es la fuente del bug clásico del proyecto: un precio
 * llega como "1500.00" y `precio > 100` da false sin que nadie se entere. Con
 * estos tipos, olvidarse el `Number()` en el mapper no compila.
 *
 * Solo lee. No modifica la base.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import pg from "pg";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error(
    "Falta DATABASE_URL. Copiá .env.example a .env.local y completalo.\n" +
      "Este script se corre con: npm run db:types",
  );
  process.exit(1);
}

const SALIDA = "src/lib/db/schema.types.ts";

/**
 * Tipo de Postgres → tipo de TypeScript, según lo que devuelve el driver `pg`.
 *
 * La clave es `udt_name` (el nombre interno), no `data_type`: `data_type` dice
 * "USER-DEFINED" para todos los enum y "ARRAY" para todos los arrays, que no
 * alcanza para distinguirlos.
 */
const TIPOS = {
  // Enteros que entran en un Number de JS.
  int2: "number",
  int4: "number",
  float4: "number",
  float8: "number",
  // ⚠️ pg los devuelve como STRING. Ver el comentario de arriba.
  numeric: "string",
  int8: "string",
  money: "string",
  // Texto.
  text: "string",
  varchar: "string",
  bpchar: "string",
  char: "string",
  uuid: "string",
  inet: "string",
  cidr: "string",
  macaddr: "string",
  citext: "string",
  // Fechas: el driver ya las convierte a Date.
  date: "Date",
  timestamp: "Date",
  timestamptz: "Date",
  time: "string",
  timetz: "string",
  interval: "string",
  // Otros.
  bool: "boolean",
  json: "unknown",
  jsonb: "unknown",
  bytea: "Buffer",
};

const client = new pg.Client({ connectionString: DATABASE_URL });
await client.connect();

// ── 1. Los enum y sus valores ────────────────────────────────────────────────
const { rows: enums } = await client.query(`
  -- enumlabel es de tipo "name", y el driver no parsea un array de "name" a un
  -- array de JS (devuelve el string crudo "{a,b,c}"). El cast a text sí lo parsea.
  SELECT t.typname AS nombre, array_agg(e.enumlabel::text ORDER BY e.enumsortorder) AS valores
  FROM pg_type t
  JOIN pg_enum e ON e.enumtypid = t.oid
  JOIN pg_namespace n ON n.oid = t.typnamespace
  WHERE n.nspname = 'public'
  GROUP BY t.typname
  ORDER BY t.typname
`);

const enumPorNombre = new Map(enums.map((e) => [e.nombre, e.valores]));

// ── 2. Tablas y vistas con sus columnas ──────────────────────────────────────
const { rows: columnas } = await client.query(`
  SELECT
    c.table_name    AS tabla,
    t.table_type    AS clase,
    c.column_name   AS columna,
    c.udt_name      AS udt,
    c.data_type     AS tipo_sql,
    c.is_nullable = 'YES' AS nullable,
    -- ATENCION: hay DOS formas de que una columna se autogenere, y hay que
    -- mirar las dos:
    --
    --   id integer DEFAULT nextval('x_id_seq')       -> column_default
    --   id integer GENERATED BY DEFAULT AS IDENTITY  -> is_identity
    --
    -- En una columna IDENTITY, column_default viene NULL. Mirando solo esa
    -- columna se concluye que no se autogenera, y en este proyecto eso llevo a
    -- diagnosticar como "roto" el alta de clientes, que funciona perfecto:
    -- cliente, mascota y turno son IDENTITY; articulo, proveedor y deposito
    -- usan nextval.
    (c.column_default IS NOT NULL OR c.is_identity = 'YES') AS tiene_default,
    c.is_identity = 'YES' AS es_identity
  FROM information_schema.columns c
  JOIN information_schema.tables t
    ON t.table_schema = c.table_schema AND t.table_name = c.table_name
  WHERE c.table_schema = 'public'
    AND t.table_type IN ('BASE TABLE', 'VIEW')
  ORDER BY c.table_name, c.ordinal_position
`);

await client.end();

if (columnas.length === 0) {
  console.error("La base no devolvió ninguna columna del esquema `public`. ¿DATABASE_URL apunta a la base correcta?");
  process.exit(1);
}

// ── 3. Armar el archivo ──────────────────────────────────────────────────────

/** snake_case → PascalCase, para el nombre del tipo de un enum. */
const aPascal = (s) => s.replace(/(^|_)([a-z0-9])/g, (_, __, c) => c.toUpperCase());

/** Un identificador que no sea un nombre JS válido se emite entre comillas. */
const clave = (s) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(s) ? s : JSON.stringify(s));

function tipoTs(col) {
  // Los arrays vienen con el udt del elemento prefijado con "_": _int4, _text.
  if (col.udt.startsWith("_")) {
    const base = col.udt.slice(1);
    const interno = enumPorNombre.has(base) ? aPascal(base) : (TIPOS[base] ?? "unknown");
    return `${interno}[]`;
  }
  if (enumPorNombre.has(col.udt)) return aPascal(col.udt);
  return TIPOS[col.udt] ?? "unknown";
}

const partes = [];

partes.push(`// ─────────────────────────────────────────────────────────────────────────────
// GENERADO AUTOMÁTICAMENTE — NO EDITAR A MANO.
//
//   Regenerar:  npm run db:types
//   Generador:  scripts/db-types.mjs
//
// Describe el esquema REAL de la base, con los tipos que devuelve el driver
// \`pg\` (ojo: numeric y bigint llegan como string, no como number).
//
// Cómo se usa: los tipos \`*Row\` de cada módulo se derivan de acá en vez de
// escribirse a mano, así un cambio en la base rompe la compilación en vez de
// fallar en producción.
//
//   import type { Row } from "@/lib/db/schema.types";
//
//   export type ProveedorRow = Pick<
//     Row<"proveedor">,
//     "id" | "razon_social" | "cuit" | "estado"
//   >;
// ─────────────────────────────────────────────────────────────────────────────
`);

// Enums
if (enums.length > 0) {
  partes.push(`// ── Enums ────────────────────────────────────────────────────────────────────\n`);
  for (const e of enums) {
    partes.push(
      `export type ${aPascal(e.nombre)} = ${e.valores.map((v) => JSON.stringify(v)).join(" | ")};\n`,
    );
  }
  partes.push("");
}

// Tablas y vistas
const porTabla = new Map();
for (const col of columnas) {
  if (!porTabla.has(col.tabla)) porTabla.set(col.tabla, { clase: col.clase, cols: [] });
  porTabla.get(col.tabla).cols.push(col);
}

const tablas = [...porTabla].filter(([, v]) => v.clase === "BASE TABLE");
const vistas = [...porTabla].filter(([, v]) => v.clase === "VIEW");

function bloque(titulo, entradas, nombreInterfaz) {
  if (entradas.length === 0) return;
  partes.push(`// ── ${titulo} ${"─".repeat(Math.max(0, 72 - titulo.length))}\n`);
  partes.push(`export interface ${nombreInterfaz} {`);
  for (const [tabla, { cols }] of entradas) {
    partes.push(`  ${clave(tabla)}: {`);
    for (const col of cols) {
      const t = tipoTs(col);
      // "auto" = la base la completa sola, así que el INSERT puede omitirla.
      // Se distingue identity de default para que quede claro de dónde sale.
      const nota = col.es_identity
        ? "  // auto (identity)"
        : col.tiene_default
          ? "  // auto (default)"
          : "";
      partes.push(`    ${clave(col.columna)}: ${t}${col.nullable ? " | null" : ""};${nota}`);
    }
    partes.push(`  };`);
  }
  partes.push(`}\n`);
}

bloque("Tablas", tablas, "DbTables");
bloque("Vistas", vistas, "DbViews");

partes.push(`// ── Helpers ──────────────────────────────────────────────────────────────────

/** La fila de una tabla: \`Row<"proveedor">\`. */
export type Row<T extends keyof DbTables> = DbTables[T];

/** La fila de una vista: \`ViewRow<"vista_cuenta_corriente_proveedor">\`. */
export type ViewRow<T extends keyof DbViews> = DbViews[T];
`);

mkdirSync(dirname(SALIDA), { recursive: true });
writeFileSync(SALIDA, partes.join("\n"), "utf8");

const sinMapear = [
  ...new Set(
    columnas
      .filter((c) => tipoTs(c).startsWith("unknown"))
      .map((c) => `${c.udt} (${c.tabla}.${c.columna})`),
  ),
];

console.log(`✓ ${SALIDA}`);
console.log(`  ${tablas.length} tablas, ${vistas.length} vistas, ${enums.length} enums`);
if (sinMapear.length > 0) {
  console.log(`\n  Tipos sin mapear (salen como \`unknown\`), agregalos a TIPOS si los necesitás:`);
  for (const t of sinMapear) console.log(`    · ${t}`);
}
